---
name: test-network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.xxzx.com
    certificateAuthorities:
    - ca.org1.xxzx.com
peers:
  peer0.org1.xxzx.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICFjCCAb2gAwIBAgIUKmpkvAL9oHCn6Equp/JI5r2QWzowCgYIKoEcz1UBg3Uw
          aDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQK
          EwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMt
          Y2Etc2VydmVyMB4XDTIxMDgyNjAzMTkwMFoXDTM2MDgyMjAzMTkwMFowaDELMAkG
          A1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQKEwtIeXBl
          cmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMtY2Etc2Vy
          dmVyMFkwEwYHKoZIzj0CAQYIKoEcz1UBgi0DQgAEJSQufeTsck5t45GFqqf4YIqu
          0P7ncYzADuilbNvte3fP+vQwl2pQCkU+/Y+8FsGziNyoP3grBh7mc8YtOY39naNF
          MEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYE
          FOhVH7PxEcecnXS5Y9uFz/oV6AUHMAoGCCqBHM9VAYN1A0cAMEQCIEL6BAsKc8hq
          w3kamaivCBJ5k9aUCOM7HPYo1I3xjBnWAiAWEcYVpBePa9YXP9C8/jOaXfpKjW4d
          3h8MsVgi7imduQ==
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org1.xxzx.com
      hostnameOverride: peer0.org1.xxzx.com
certificateAuthorities:
  ca.org1.xxzx.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICFjCCAb2gAwIBAgIUKmpkvAL9oHCn6Equp/JI5r2QWzowCgYIKoEcz1UBg3Uw
          aDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQK
          EwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMt
          Y2Etc2VydmVyMB4XDTIxMDgyNjAzMTkwMFoXDTM2MDgyMjAzMTkwMFowaDELMAkG
          A1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQKEwtIeXBl
          cmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMtY2Etc2Vy
          dmVyMFkwEwYHKoZIzj0CAQYIKoEcz1UBgi0DQgAEJSQufeTsck5t45GFqqf4YIqu
          0P7ncYzADuilbNvte3fP+vQwl2pQCkU+/Y+8FsGziNyoP3grBh7mc8YtOY39naNF
          MEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYE
          FOhVH7PxEcecnXS5Y9uFz/oV6AUHMAoGCCqBHM9VAYN1A0cAMEQCIEL6BAsKc8hq
          w3kamaivCBJ5k9aUCOM7HPYo1I3xjBnWAiAWEcYVpBePa9YXP9C8/jOaXfpKjW4d
          3h8MsVgi7imduQ==
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
